apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: default
  labels:
    app:  python-api
spec:
  selector:
    matchLabels:
      app: python-api
  replicas: 1
  template:
    metadata:
      labels:
        app:  python-api
    spec:
      containers:
      - name:  python-api
        image: samuelkadima/k8s-and-docker:v1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  namespace: default
spec:
  selector:
    app: python-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
